name: walk_with_god
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.9

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^0.5.0
  firebase_analytics: ^6.0.0
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2
  firebase_storage: ^4.0.0
  fluttertoast: ^3.1.3
  intl:
  url_launcher: ^5.4.11
  flutter_visibility_aware: ^0.0.2+1
  provider: ^4.3.2
  auto_size_text:
  flutter_spinkit:
  google_sign_in:
  apple_sign_in: ^0.1.0
  image_cropper: ^1.3.1
  image_picker: ^0.6.7+7
  wakelock: ^0.1.4+2
  flutter_switch: ^0.1.1
  path_provider: ^1.6.14
  cached_network_image: ^2.3.2+1
  flutter_cache_manager: ^1.4.2
  connectivity: ^0.4.9+2
  flutter_logs: ^2.1.3
  flutter_svg: ^0.19.3
  flutter_email_sender: ^3.0.1
  pin_code_fields: ^6.0.1
  launch_review: ^2.0.0
  new_version: ^0.0.5
  flutter_local_notifications: ^3.0.2
  firebase_messaging: ^7.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"
  cloud_firestore_mocks: ^0.5.2+1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"
  adaptive_icon_background: "#191919"
  adaptive_icon_forground: "assets/images/app_logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/placeholder.png
    - assets/images/default_profile_picture.jpg
    - assets/images/wechat.png
    - assets/images/friends_circle.png
    - assets/images/facebook.png
    - assets/images/email.png
    - assets/images/app_logo.png
    - assets/icons/back.svg
    - assets/icons/forward.svg
    - assets/icons/save.svg
    - assets/icons/save_border.svg
    - assets/icons/search.svg
    - assets/icons/comment.svg
    - assets/icons/heart.svg
    - assets/icons/heart_border.svg
    - assets/icons/share.svg
    - assets/icons/setting.svg
    - assets/icons/google.svg
    - assets/icons/phone.svg
    - assets/icons/apple.svg
    - assets/icons/email.svg
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Song
      fonts:
        - asset: fonts/SourceHanSerifCN-Heavy.otf
    - family: Hei
      fonts:
        - asset: fonts/SourceHanSansCN-Medium.otf
          weight: 500
        - asset: fonts/SourceHanSansCN-Normal.otf
          weight: 300
        - asset: fonts/SourceHanSansCN-Light.otf
          weight: 200
    - family: Rajdhani
      fonts:
        - asset: fonts/Rajdhani-Bold.ttf
          weight: 500
        - asset: fonts/Rajdhani-Regular.ttf
          weight: 300
